version: '3.1'
services:
    teamspeak:
        image: teamspeak
        restart: always
        ports:
            - 9987:8887/udp
            - 10011:18011
            - 30033:38033
        environment:
            TS3SERVER_LICENSE: accept
        volumes:
            - ./teamspeak-server:/var/ts3server/
